version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"

  nextjs_build:
    image: node:18-alpine
    container_name: portfolio_builder
    working_dir: /app
    volumes:
      - ./portfolio:/app
      - ./portfolio/dist:/app/dist
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./portfolio/dist:/usr/share/nginx/html/portfolio:ro

    depends_on:
      - web
      - nextjs

volumes:
  static_volume:
  media_volume:
